### ISSUE TITLE
New DiceBear Avatars version

### ISSUE THREAD

**Issue by FlorianKoerner** [pascallaliberte/stimulus-turbolinks-demo#6]
I am very happy to see that this project uses DiceBear Avatars. 🎉

A new version of DiceBear Avatars has just been released. The new API endpoint (v2) now supports SVG and identicons.

The documentation can be found here: https://avatars.dicebear.com

However, the old API point (v1) still works.

**Comment by pascallaliberte** [comment]
Thanks for making these @FlorianKoerner! Victoria Owen is happy her complexion just got more definition
